version: 2.1

run_on_tag: &run_on_tag
  filters:
    tags: { only: "/.*/" }

parameters:
  rollback:
    type: boolean
    default: false

commands:
  save_go_cache:
    steps:
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  restore_go_cache:
    steps:
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

  configure_version:
    steps:
      - run:
          name: Configure App Version
          command: |
            echo 'export APP_VERSION='$CIRCLE_TAG >> $BASH_ENV
            source $BASH_ENV

  configure_rollback:
    steps:
      - run:
          name: Configure rollback
          command: |
            echo 'export APP_VERSION='$(git tag --sort=creatordate | tail -n 2 | head -n 1) >> $BASH_ENV
            source $BASH_ENV

jobs:
  lint:
    docker:
      - image: cimg/go:1.23
    steps:
      # Checkout the code as the first step.
      - checkout
      - restore_go_cache
      - run:
          name: Install Dependencies
          command: go mod download
      - save_go_cache
      - run:
          name: Lint the code
          command: make lint

  test:
    docker:
      - image: cimg/go:1.23
    steps:
      # Checkout the code as the first step.
      - checkout
      - restore_go_cache
      - run:
          name: Install Dependencies
          command: go mod download
      - save_go_cache
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
            gotestsum -- -coverprofile=/tmp/test-reports/cover.out ./internal/...

      - store_test_results:
          path: /tmp/test-reports

  build:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - restore_go_cache
      - run:
          name: Install Dependencies
          command: go mod download
      - save_go_cache
      - configure_version
      - run:
          name: Build the application
          command: |
            make build VERSION=$APP_VERSION
      - persist_to_workspace:
          root: .
          paths:
            - ./bin/app
            - Dockerfile
            - Makefile

  build-image:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - configure_version
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            make build-image VERSION=$APP_VERSION
      - run:
          name: Save docker image
          command: |
            docker save -o /tmp/app.tar app:latest

  deploy:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - configure_version
      - run:
          name: Deploy app << pipeline.git.tag >>
          command: echo "Deploying app version $APP_VERSION"

  rollback:
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - configure_version
      - configure_rollback
      - run:
          name: Rollback to previous version
          command: echo "Rolling back to previous version $APP_VERSION"

workflows:
  lint-test-build:
    unless: << pipeline.parameters.rollback >>
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test

  deploy_app:
    when:
      matches:
        pattern: "/[0-9]+(.[0-9]+){2}/"
        value: << pipeline.git.tag >>
    jobs:
      - lint:
          <<: *run_on_tag
      - test:
          <<: *run_on_tag

      - build:
          <<: *run_on_tag
          requires:
            - lint
            - test
      - deploy:
          <<: *run_on_tag
          requires:
            - build

  rollback_app:
    when:
      matches:
        pattern: "/[0-9]+(.[0-9]+){2}-rollback/"
        value: << pipeline.git.tag >>
    jobs:
      - rollback:
          <<: *run_on_tag

  rollback_previous:
    when: << pipeline.parameters.rollback >>
    jobs:
      - approval:
          name: 🚒 Rollback to previous version
          type: approval
      - rollback:
          requires:
            - 🚒 Rollback to previous version
